language: cpp

env:
  - TARGET="Android-ARM"
  - TARGET="Linux-ARM"
  - TARGET="Linux-X86"
  - TARGET="Linux-X86_64"
  - TARGET="Linux-X86_64" LLGS_TESTS="1"

matrix:
  allow_failures:
    - env: TARGET="Linux-X86_64" LLGS_TESTS="1"
  fast_finish: true

before_install:
  - [ "$TARGET" = "Linux-ARM" ]     && sudo add-apt-repository -y ppa:linaro-maintainers/toolchain
  - [ "$TARGET" = "Linux-X86" ]     && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - [ "$TARGET" = "Linux-X86_64" ]  && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - [ "$LLGS_TESTS" = "1" ]         && sudo add-apt-repository -y ppa:andykimpe/cmake
  - sudo apt-get update

install:
  - [ "$TARGET" = "Android-ARM" ]   && ./Support/Scripts/prepare-android-toolchain.sh "arm"
  - [ "$TARGET" = "Linux-ARM" ]     && sudo apt-get install -y g++-arm-linux-gnueabi
  - [ "$TARGET" = "Linux-X86" ]     && sudo apt-get install -y g++-4.8-multilib
  - [ "$TARGET" = "Linux-X86_64" ]  && sudo apt-get install -y g++-4.8
  # Running LLGS tests requires a recent enough cmake (for the LLVM cmake
  # step), and an install of lldb (for the tests to be able to use the lldb
  # python library without us building it).
  - [ "$LLGS_TESTS" = "1" ]         && sudo apt-get install -y cmake swig lldb-3.3

before_script:
  - mkdir -p build && cd build

script:
  - cmake -DCMAKE_TOOLCHAIN_FILE="../Support/CMake/Toolchain-${TARGET}.cmake" ..
  - make
  - if [ "$LLGS_TESTS" = "1" ] && ../Support/Testing/run-llgs-tests.sh
