##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##

dist: trusty
sudo: required
language: generic
branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    # Misc targets
    - os: linux
      env: TARGET="Linux-X86"      LLDB_TESTS="DumpDynamic"  CLANG="0" COVERAGE="1" PLATFORM="1"
    - os: linux

# Use travis_retry during install to reduce the impact of network failures.
before_install: travis_retry ./Support/Testing/Travis/before-install.py
install:        travis_retry ./Support/Testing/Travis/install.py
script:         ./Support/Testing/Travis/script.sh
after_success:  ./Support/Testing/Travis/after_success.sh
