##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##


docker_config: &docker_config
  docker:
    - image: sas42/ds2-build-env:2018-02-01_18-03-00

configure_step: &configure_step
  run:
    name: Configure
    command: mkdir build && cd build && cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../Support/CMake/Toolchain-${TARGET-${CIRCLE_JOB}}.cmake ..

build_step: &build_step
  run:
    name: Build
    command: ninja -C build -v

test_step: &test_step
  run:
    name: Test
    command: cd build && ../Support/Scripts/run-lldb-tests.sh

check_dirty_step: &check_dirty_step
  run:
    name: Check for dirty state
    command: git --no-pager diff --exit-code

start_android_emulator_step: &start_android_emulator_step
  run:
    name: Start Android emulator
    command: ./Support/Scripts/start-android-emulator.sh
    background: true

build_only_defaults: &build_only_defaults
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step

build_and_test_defaults: &build_and_test_defaults
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step
    - *test_step

build_and_test_android: &build_and_test_android
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step
    - *start_android_emulator_step
    - *test_step

version: 2
jobs:
  Style:
    <<: *docker_config
    steps:
      - checkout
      - run:
          name: Apply clang-format
          command: find Sources Headers -type f -exec clang-format-5.0 -i -style=file {} \;
      - *check_dirty_step
  Registers:
    <<: *docker_config
    environment:
      CLANG_FORMAT: clang-format-5.0
    steps:
      - checkout
      - run:
          name: Generate register descriptors
          command: ./Support/Scripts/generate-register-descriptors.sh
      - *check_dirty_step
  Documentation:
    <<: *docker_config
    environment:
      ENCRYPTION_LABEL: c06a05533acc
    steps:
      - checkout
      - run:
          name: Generate documentation
          command: ./Support/Scripts/generate-documentation.sh
  Linux-X86:
    <<: *build_and_test_defaults
  Linux-X86-platform:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86
      PLATFORM: 1
  Linux-X86_64:
    <<: *build_and_test_defaults
  Linux-X86_64-platform:
    <<: *build_and_test_defaults
    environment:
      TARGET: Linux-X86_64
      PLATFORM: 1
  Android-ARM:
    <<: *build_and_test_android
    environment:
      PLATFORM: 1
  Android-ARM64:
    <<: *build_only_defaults
  Android-X86:
    <<: *build_only_defaults
  Android-X86_64:
    <<: *build_only_defaults
  Tizen-X86:
    <<: *build_only_defaults
  Tizen-ARM:
    <<: *build_only_defaults
  MinGW-X86:
    <<: *build_only_defaults
  MinGW-X86_64:
    <<: *build_only_defaults
  Darwin-X86_64:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install cmake ninja flex bison
      - checkout
      - *configure_step
      - *build_step

workflows:
  version: 2
  build_and_test:
    jobs:
      - Style
      - Registers
      - Documentation
      - Linux-X86
      - Linux-X86_64
      - Android-ARM
      - Android-ARM64
      - Android-X86
      - Android-X86_64
      - Tizen-X86
      - Tizen-ARM
      - MinGW-X86
      - MinGW-X86_64
      - Darwin-X86_64
