##
## Copyright (c) 2014-present, Facebook, Inc.
## All rights reserved.
##
## This source code is licensed under the University of Illinois/NCSA Open
## Source License found in the LICENSE file in the root directory of this
## source tree. An additional grant of patent rights can be found in the
## PATENTS file in the same directory.
##


docker_config: &docker_config
  docker:
    - image: sas42/ds2-build-env

configure_step: &configure_step
  run:
    name: Configure
    command: mkdir build && cd build && cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../Support/CMake/Toolchain-$CIRCLE_JOB.cmake ..

build_step: &build_step
  run:
    name: Build
    command: ninja -C build -v

test_step: &test_step
  run:
    name: Test
    command: test -z "$LLDB_TESTS" || (cd build && ../Support/Scripts/run-lldb-tests.sh)

defaults: &defaults
  <<: *docker_config
  steps:
    - checkout
    - *configure_step
    - *build_step
    - *test_step

version: 2
jobs:
  Style:
    <<: *docker_config
    steps:
      - checkout
      - run:
          name: Apply clang-format
          command: find Sources Headers -type f -exec clang-format-5.0 -i -style=file {} \;
      - run:
          name: Check style differences
          command: git --no-pager diff --exit-code
  Android-ARM64:
    <<: *defaults
  Android-X86_64:
    <<: *defaults
  Tizen-X86:
    <<: *defaults
  Tizen-ARM:
    <<: *defaults
  MinGW-X86:
    <<: *defaults
  MinGW-X86_64:
    <<: *defaults
  Darwin-X86_64:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install cmake ninja flex bison
      - checkout
      - *configure_step
      - *build_step
      - *test_step

workflows:
  version: 2
  build_and_test:
    jobs:
      - Style
      - Android-ARM64
      - Android-X86_64
      - Tizen-X86
      - Tizen-ARM
      - MinGW-X86
      - MinGW-X86_64
      - Darwin-X86_64
